'use client';
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
const topics=['หาลูกค้าใหม่ให้คลินิก','เปลี่ยนคนทักให้เป็นคนนัด','ดูแลลูกค้าเก่าให้กลับมาใช้บริการ','ยังไม่แน่ใจ อยากคุยก่อน'];

export default function LeadForm(){const [consent,setConsent]=useState(false);const [complete,setComplete]=useState(false);return <form className="lead-form" onSubmit={e=>{e.preventDefault();if(consent)setComplete(true)}}><div className="form-title"><h3>ให้ทีมติดต่อกลับ</h3></div><p className="demo-note">ทดลองกรอกได้ ข้อมูลจะยังไม่ถูกบันทึกหรือส่งถึงทีม Sellsuki</p><div className="form-fields"><label htmlFor="lead-name">ชื่อผู้ติดต่อ <b>*</b><Input id="lead-name" name="name" required maxLength={100} autoComplete="name" placeholder="ชื่อที่ให้ทีมเรียกคุณ"/></label><label htmlFor="clinic-name">ชื่อคลินิก <b>*</b><Input id="clinic-name" name="clinic" required maxLength={150} autoComplete="organization" placeholder="ชื่อคลินิกของคุณ"/></label><label htmlFor="lead-phone">เบอร์โทรศัพท์ <b>*</b><Input id="lead-phone" name="phone" type="tel" required inputMode="tel" pattern="[+0-9 ()-]{8,20}" autoComplete="tel" placeholder="เบอร์ที่สะดวกให้ติดต่อกลับ"/></label><label htmlFor="lead-email">อีเมล<Input id="lead-email" name="email" type="email" autoComplete="email" placeholder="อีเมลของคุณ (ไม่บังคับ)"/></label><label className="full-field" htmlFor="clinic-question">อยากให้เราช่วยเรื่องไหน?<Select name="topic"><SelectTrigger id="clinic-question" className="topic-trigger"><SelectValue placeholder="เลือกเรื่องที่อยากให้ช่วย"/></SelectTrigger><SelectContent className="topic-menu" alignItemWithTrigger={false}>{topics.map(t=><SelectItem key={t} value={t} className="topic-item">{t}</SelectItem>)}</SelectContent></Select></label></div><div className="consent"><Checkbox id="lead-consent" checked={consent} onCheckedChange={v=>{setConsent(v===true);setComplete(false)}}/><label htmlFor="lead-consent">ยินยอมให้ใช้ข้อมูลที่กรอกเพื่อติดต่อกลับเรื่องบริการของ Sellsuki</label></div><button className="button submit-button" type="submit" disabled={!consent}>ให้ทีมติดต่อกลับ <ArrowRight size={22} strokeWidth={1.9} aria-hidden="true"/></button>{complete&&<div className="form-result" role="status"><CheckCircle2 size={22}/><p><strong>ทดลองกรอกครบแล้ว</strong><br/>นี่คือหน้าตัวอย่าง ยังไม่มีการส่งหรือบันทึกข้อมูล</p></div>}</form>}
