import { ArrowUpRight, ArrowRight, CalendarCheck, MapPin, Search, Check, Camera, Compass, Megaphone, Code2 } from 'lucide-react';
import LeadForm from './lead-form';
const challenges=[
 {title:'คู่แข่งในพื้นที่เยอะขึ้น',text:'ลูกค้ามีหลายคลินิกให้เลือก ทั้งใกล้บ้านและใกล้ที่ทำงาน ทำอย่างไรให้เขานึกถึงเรา?'},
 {title:'บนออนไลน์ ก็มีคู่แข่งเต็มไปหมด',text:'ลูกค้าเห็นทั้งโฆษณา รีวิว และโปรโมชันทุกวัน คลินิกเราจะเล่าอะไรให้เขาหยุดดู?'},
 {title:'ลูกค้าใช้เวลาตัดสินใจนานขึ้น',text:'ทักมาถามแล้วกลับไปดูข้อมูล เปรียบเทียบอีกหลายที่ ระหว่างนั้นเราติดต่อดูแลเขาอย่างไร?'},
 {title:'วิธีเดิมเริ่มไม่ได้ผลเหมือนเดิม',text:'คอนเทนต์และโปรโมชันที่เคยได้ผล วันนี้อาจมีคนสนใจน้อยลง ควรลองปรับอะไรดี?'},
 {title:'ลูกค้าเก่าไม่กลับมา',text:'เคยมาใช้บริการแล้ว แต่ไม่ได้ติดต่อกันอีก คลินิกจะชวนเขากลับมาดูแลตัวเองอย่างไร?'},
 {title:'ทีมการตลาดยังไม่เข้าใจคลินิก',text:'มีทีมทำงานให้ แต่สิ่งที่สื่อสารยังไม่ตรงกับจุดเด่นของคลินิก ต้องอธิบายกันใหม่อยู่บ่อย ๆ'}
];
const solutions=[
 {n:'01',title:'ช่วยให้คนรู้จักคลินิก',desc:'ถ่ายวิดีโอเล่าจุดเด่นของคลินิก ทำรีวิวจากประสบการณ์จริง และยิงโฆษณาให้เข้าถึงคนที่สนใจบริการของคุณ',tags:'วิดีโอ · โฆษณา · รีวิว',note:'ดูผล: คนสนใจมาจากช่องทางไหน',alt:'หมา Sellsuki ถ่ายวิดีโอ พร้อมสื่อโฆษณาและรีวิว'},
 {n:'02',title:'โดดเด่นกว่าคู่แข่ง',desc:'เลือก Influencer ที่เหมาะกับคลินิก เล่าความเชี่ยวชาญของคุณหมอ พร้อมปรับเว็บไซต์และข้อมูลบน Google Maps ให้ลูกค้าหาเจอและเห็นเหตุผลที่จะเลือกคุณ',tags:'Influencer · Google Maps · เว็บไซต์',note:'ดูผล: ลูกค้าค้นหาและเข้ามารู้จักเราจากที่ไหน',alt:'หมา Sellsuki เป็น Influencer แนะนำคลินิก พร้อมเว็บไซต์และหมุดแผนที่'},
 {n:'03',title:'ช่วยติดตามคนที่ทักมา',desc:'แยกกลุ่มคนที่ทัก LINE ตามบริการที่สนใจและสถานะการนัดหมาย ให้ทีมรู้ว่าใครรอข้อมูล ใครพร้อมนัด และควรคุยกับแต่ละคนต่ออย่างไร',tags:'LINE · จัดกลุ่ม · ติดตาม',note:'ดูผล: ติดตามคนที่ทักมาครบหรือยัง',alt:'กบ LINE จัดข้อความที่เข้ามาเป็นกลุ่มตามความสนใจ'},
 {n:'04',title:'ช่วยให้การนัดหมายง่ายขึ้น',desc:'ส่งรายละเอียดและข้อความเตือนนัดผ่าน LINE ให้ลูกค้ายืนยันหรือขอเลื่อนนัดได้สะดวก และให้ทีมคลินิกเตรียมดูแลได้ทัน',tags:'LINE · ยืนยันนัด · เตือนนัด',note:'ดูผล: นัดกี่คน มาใช้บริการจริงกี่คน',alt:'กบ LINE ช่วยส่งข้อความแจ้งเตือนนัดหมายบนโทรศัพท์'}
];
const teams=[{role:'กลยุทธ์และดูแลลูกค้า',icon:Compass,work:'คุยกับคุณให้เข้าใจบริการ ลูกค้า และเป้าหมาย วางแผนงาน พร้อมประสานงานระหว่างทีม',label:'ทีมงานที่คุณคุยด้วยตั้งแต่เริ่ม'}, {role:'คอนเทนต์และครีเอทีฟ',icon:Camera,work:'ช่วยคิดเรื่องที่จะเล่า เขียนข้อความ และวางภาพให้คนเข้าใจจุดเด่นของคลินิกและคุณหมอ',label:'ทีมงานที่ช่วยเล่าเรื่องคลินิก'}, {role:'โฆษณาและการค้นหา',icon:Megaphone,work:'ดูแลโฆษณา เว็บไซต์ และการค้นหาในพื้นที่ พร้อมติดตามว่าคนสนใจมาจากช่องทางไหน',label:'ทีมงานที่ช่วยให้ลูกค้าหาคุณเจอ'}, {role:'LINE ระบบและข้อมูล',icon:Code2,work:'วางการจัดกลุ่มลูกค้า การติดตาม และข้อมูลที่ทีมคลินิกใช้ทำงานต่อได้',label:'ทีมงานที่ช่วยให้คลินิกดูแลลูกค้าได้ครบ'}];
const executives=[
 {name:'Pattara Thurnsiri',role:'CEO & Co-Founder',label:'เข้าใจธุรกิจก่อนวางแผน',idea:'เริ่มจากเป้าหมายของคลินิก แล้ววางทิศทางให้การตลาด การขาย และการดูแลลูกค้าไปด้วยกัน',image:'/executive-nuntawit.png'},
 {name:'Nuntawit Janwaowam',role:'CPO & Co-Founder',label:'ออกแบบบริการจากโจทย์จริง',idea:'เลือกบริการและเครื่องมือให้ตอบสิ่งที่คลินิกต้องการ และช่วยให้ทีมทำงานได้สะดวกขึ้น',image:'/executive-pattara.png'},
 {name:'Pitchaporn Prakaiharn',role:'Chief Operating Officer',label:'ทำให้แผนเกิดขึ้นได้จริง',idea:'เชื่อมการทำงานของแต่ละทีม กำหนดหน้าที่ให้ชัด และติดตามงานให้เดินตามแผน',image:'/executive-pitchaporn.png'},
 {name:'Watchrapong Agsonchu',role:'Chief Technology Officer',label:'ให้ระบบช่วยแบ่งเบางาน',idea:'ลดงานซ้ำ เชื่อมข้อมูล และทำให้ทีมใช้ข้อมูลดูแลลูกค้าได้ง่ายขึ้น',image:'/executive-watchrapong.png'}
];
function PhotoSlot({label}:{label:string}){return <div className="photo-slot"><Camera aria-hidden="true"/><span>{label}</span><small>พื้นที่สำหรับภาพจริง</small></div>}
export default function Home(){return <>
<a className="skip" href="#main">ข้ามไปเนื้อหา</a>
<header className="header"><div className="nav wrap"><a href="https://www.sellsuki.co.th/" className="brand-logo" aria-label="Sellsuki หน้าแรก"><img src="/sellsuki-logo.png" alt="Sellsuki" width="1667" height="834"/></a><nav aria-label="เมนูหลัก"><a href="#solutions">บริการของ Sellsuki</a><a href="#team">ทีมการตลาดของเรา</a><a href="#experience">กว่า 10 ปีที่เติบโตไปกับธุรกิจไทย</a></nav><a className="button small" href="#talk">คุยกับทีม Sellsuki <ArrowUpRight size={17}/></a></div></header>
<main id="main">
<section className="hero wrap"><div className="hero-copy"><div className="hero-kicker">บริการการตลาดสำหรับคลินิกความงามและสุขภาพ</div><h1>เปลี่ยนคนที่ทักคลินิก<br/>มาแล้วหาย ให้เป็นลูกค้า<br/><em>นัดหมายและมาซ้ำ</em></h1><p>จบปัญหาทักมาแล้วแต่ไม่ได้นัด หรือไม่มีเวลาตามลูกค้าเก่า ให้ Sellsuki ดูแลครบจบทั้งคอนเทนต์ โฆษณา จัดการนัดหมาย และการดูแลลูกค้าเดิม โดยเริ่มจากเรื่องที่คลินิกอยากแก้ที่สุดก่อน</p><div className="hero-actions"><a className="button" href="#talk">ปรึกษาการตลาดคลินิก <ArrowUpRight size={20}/></a><a className="text-link" href="#solutions">บริการของ Sellsuki <ArrowRight size={17}/></a></div></div><div className="hero-visual"><div className="photo-frame"><img src="/clinic-partners.png" alt="ภาพประกอบเจ้าของคลินิกพูดคุยเรื่องธุรกิจอย่างเป็นกันเอง" width="1448" height="1086"/></div><div className="year-stamp"><b>10+</b><span>ปีที่ทำงานกับ<br/>ธุรกิจไทย</span></div></div></section>
<section className="section wrap" id="challenges"><div className="challenge-intro"><h2>คลินิกของคุณกำลังเจอเรื่องไหนอยู่บ้าง?</h2><p>ลองดูว่าเรื่องไหนตรงกับสิ่งที่คุณกำลังเจอ</p></div><div className="challenge-grid">{challenges.map((c,i)=><article key={c.title}><img className="challenge-banner-image" src={`/challenge-${i+1}.png`} alt="" width="1536" height="1024" loading="lazy"/><div className="challenge-banner-copy"><span className="challenge-number">0{i+1}</span><h3>{c.title}</h3><p>{c.text}</p></div></article>)}</div></section>
<section id="solutions" className="solutions section"><div className="wrap"><div className="section-heading"><div><div className="eyebrow">บริการของ Sellsuki</div><h2>ช่วยหาลูกค้าใหม่<br/><span className="blue">ตั้งแต่ทำให้รู้จัก จนถึงวันนัดหมาย</span></h2></div><p>เลือกเริ่มจากส่วนที่คลินิกต้องการความช่วยเหลือ<br/>แล้วตกลงงานและหน้าที่ของแต่ละทีมให้ชัด</p></div><div className="solution-grid">{solutions.map(s=><article key={s.n} className="solution-card"><div className={`service-art ${s.n==='04'?'reminder-art':''}`}><img src={`/mascot-service-${s.n}.png`} alt={s.alt} width="1536" height="1024" loading="lazy"/>{s.n==='04'&&<div className="phone-screen-label" aria-hidden="true"><strong>LINE</strong><CalendarCheck size={24}/></div>}<span className="service-number">{s.n}</span></div><small>{s.tags}</small><h3>{s.title}</h3><p>{s.desc}</p>{s.n==='03'&&<div className="segment-preview" aria-label="ตัวอย่างกลุ่มผู้สนใจ"><span>รอข้อมูล</span><span>สนใจบริการ</span><span>พร้อมนัด</span></div>}{s.n==='04'&&<div className="line-message-preview"><small>ตัวอย่างข้อความผ่าน LINE</small><strong>แจ้งเตือนนัดหมาย 💚</strong><p>พรุ่งนี้ เวลา 14.00 น.<br/>คุณมีนัดปรึกษาที่คลินิกค่ะ</p><div><span>ยืนยันนัด</span><span>ขอเลื่อนนัด</span></div></div>}<div className="measure">{s.note}</div></article>)}</div></div></section>
<section className="section wrap examples" id="examples"><div className="center"><div className="eyebrow">ลองดูตัวอย่างใกล้ตัว</div><h2>ถ้าคลินิกติดเรื่องนี้<br/>เราจะเริ่มช่วยอย่างไร?</h2><p>ตัวอย่างแนวทางทำงาน เพื่อให้เห็นภาพก่อนคุยรายละเอียดของคลินิกคุณ</p></div>
<article className="example-row"><figure className="example-visual local-map-visual"><img src="/local-search-map.png" alt="ภาพจำลองแผนที่ค้นหาคลินิกในกรุงเทพฯ" width="1536" height="960" loading="lazy"/></figure><div className="example-copy"><div className="eyebrow">01 · คนในพื้นที่ยังไม่รู้จัก</div><h3>อยู่ใกล้กัน แต่ลูกค้าหาคลินิกเราเจอหรือยัง?</h3><p>เวลามองหาคลินิก ลูกค้าอาจเริ่มจากชื่อบริการกับย่านที่สะดวก ถ้าข้อมูลของเราหายาก เขาก็อาจไปเจอที่อื่นก่อน</p><p>เราช่วยทำเว็บไซต์และปรับข้อมูลเพื่อรองรับการค้นหาในพื้นที่ หรือ Local SEO ให้คนรู้ว่าคลินิกอยู่ที่ไหน มีบริการอะไร และติดต่ออย่างไร</p><ul><li>จัดหน้าบริการและข้อมูลพื้นที่ให้ชัด</li><li>ดูแลข้อมูลที่อยู่ เวลาเปิด และช่องทางติดต่อ</li><li>ติดตามการค้นหาและคนที่เข้ามาสอบถาม</li></ul></div></article>
<article className="example-row reverse"><div className="example-visual trust-visual"><img className="trust-photo" src="/doctor-hifu-treatment.png" alt="คุณหมอหญิงกำลังทำ HIFU ให้ผู้รับบริการ" width="2048" height="1536" loading="lazy"/><div className="trust-caption"><span>เรื่องที่ลูกค้าอยากรู้</span><strong>ใครดูแลเรา และดูแลอย่างไร?</strong><p>ความเชี่ยวชาญ · แนวคิด · ประสบการณ์ลูกค้า</p></div></div><div className="example-copy"><div className="eyebrow">02 · ยังไม่รู้จัก หรือยังไม่มั่นใจ</div><h3>ก่อนตัดสินใจ ลูกค้าอยากรู้จักคนที่จะดูแลเขา</h3><p>มีราคาและโปรโมชันแล้ว แต่ลูกค้าอาจยังไม่รู้ว่าคุณหมอถนัดอะไร เจ้าของคลินิกให้ความสำคัญกับเรื่องไหน และจะได้รับการดูแลแบบใด</p><p>เราช่วยวางเรื่องเล่าของคุณหมอและเจ้าของคลินิก หรือ CEO Branding ควบคู่กับคอนเทนต์และรีวิวจากประสบการณ์จริง ให้คลินิกมีบุคลิกชัดเจนและสื่อสารกับลูกค้าที่ต้องการได้ตรงขึ้น</p><ul><li>เล่าแนวคิดและความเชี่ยวชาญด้วยภาษาที่เข้าใจง่าย</li><li>ทำคอนเทนต์ตอบคำถามที่ลูกค้ายังลังเล</li><li>ใช้รีวิวที่ได้รับอนุญาตและข้อมูลที่คลินิกตรวจสอบแล้ว</li></ul></div></article>
<article className="example-row"><div className="example-visual line-visual"><div className="line-browser"><div className="browser-bar"><span/><span/><span/><b>LINE Official Account</b></div><div className="line-workspace"><aside><strong>คลินิกของฉัน</strong><small>แชทล่าสุด</small><div className="line-contact active">คุณมินท์ <em>สนใจ HIFU</em></div><div className="line-contact">คุณใบเฟิร์น <em>เคยใช้บริการแล้ว</em></div><div className="line-contact">คุณแพรว <em>ถึงรอบติดตาม</em></div></aside><div className="line-chat"><small>บทสนทนาล่าสุด</small><div className="chat-bubble">สนใจ HIFU ค่ะ ขอข้อมูลเพิ่มเติมได้ไหมคะ</div><div className="chat-bubble outgoing">ได้เลยค่ะ ทีมจะส่งรายละเอียดให้นะคะ</div><div className="tag-panel"><strong>จัดกลุ่มผู้สนใจ</strong><div><span>สนใจ แต่ยังไม่นัด</span><span>เคยใช้บริการแล้ว</span><span>ถึงรอบติดตาม</span></div><small>บันทึกสถานะเพื่อติดตามต่อ</small></div></div></div></div><div className="line-bottom"><Check size={18}/> ทีมดูได้ว่าใครได้รับการติดต่อแล้ว</div></div><div className="example-copy"><div className="eyebrow">03 · ลูกค้าเก่าไม่กลับมา</div><h3>มีรายชื่อลูกค้าอยู่แล้ว ลองดูแลให้ตรงกับแต่ละคน</h3><p>คนที่เพิ่งสอบถามกับคนที่เคยใช้บริการ อาจต้องการข้อมูลคนละอย่าง การส่งโปรโมชันเดียวให้ทุกคนจึงอาจไม่ตรงกับสิ่งที่เขาสนใจ</p><p>เราช่วยวางระบบ LINE ให้แยกกลุ่มตามความสนใจและประวัติการใช้บริการ เพื่อให้ทีมติดตาม เสนอสิทธิประโยชน์ และชวนกลับมาได้เหมาะสม พร้อมเก็บสถานะไม่ให้รายชื่อคนสนใจตกหล่น</p><ul><li>จัดกลุ่มลูกค้าใหม่และลูกค้าเดิม</li><li>วางข้อความและช่วงเวลาติดต่อที่เหมาะสม</li><li>ติดตามการตอบกลับ นัดหมาย และการกลับมาใช้บริการ</li></ul></div></article></section>
<section className="growth-section section"><div className="wrap"><div className="clinic-brand-banner"><img src="/clinic-growth-banner.png" alt="ภาพประกอบคลินิกความงาม การปรึกษาคุณหมอ และบริการสปาเพื่อสุขภาพ" loading="lazy"/><div className="clinic-brand-copy"><h3>เราอยากเห็นคลินิกของคุณ<br/>เติบโตไปได้ไกลกว่าเดิม</h3><p>เพราะเราเชื่อในความตั้งใจของคนทำธุรกิจ Sellsuki จึงพร้อมช่วย SME อย่างคุณ วางแผน ลงมือทำ และพัฒนาการตลาดไปด้วยกัน เพื่อให้ธุรกิจเติบโตได้ในระยะยาว</p></div></div></div></section>
<section className="section wrap leadership" id="experience"><div className="leadership-intro"><div><div className="eyebrow">กว่า 10 ปีที่เติบโตไปกับธุรกิจไทย</div><h2>เราได้ทำงานร่วมกับ SME ไทย<br/>มาตลอดกว่าทศวรรษ</h2></div><p>ตลอดเวลากว่า 10 ปี Sellsuki ได้ทำงานเคียงข้าง SME ไทยในวันที่เริ่มต้น ขยายช่องทางขาย และปรับการตลาดให้ไปต่อได้จริง ประสบการณ์เหล่านี้จึงกลายเป็นมุมมองที่ทีมพร้อมนำมาช่วยคิดให้กับคลินิกของคุณ</p></div><div className="executive-banner">{executives.map(e=><article key={e.name}><div className="executive-avatar"><img src={e.image} alt={`ภาพ ${e.name}`} width="2048" height="2048" loading="lazy"/></div><div className="executive-copy"><strong>{e.name}</strong><span className="executive-role">{e.role}</span><h3>{e.label}</h3><p>{e.idea}</p></div></article>)}</div></section>
<section className="section wrap talk lead-section" id="talk"><div className="lead-message"><div className="eyebrow">เริ่มคุยกันได้เลย</div><h2>อยากให้การตลาดของคลินิก<br/>ดีขึ้นเรื่องไหน?</h2><p>บอกเราว่าตอนนี้กำลังติดอะไร แล้วทีมจะช่วยดูว่าควรเริ่มตรงไหน ไม่จำเป็นต้องมีแผนการตลาดมาก่อน</p><div className="brand-promise"><h3>สิ่งที่เราอยากให้คุณได้จากการทำงานด้วยกัน</h3><p><Check/> <span><strong>ทำอย่างมีกลยุทธ์</strong> เข้าใจปัญหาก่อนเลือกวิธีทำ</span></p><p><Check/> <span><strong>คุยรู้เรื่อง</strong> อธิบายงาน งบประมาณ และผลที่วัดได้ให้ชัด</span></p><p><Check/> <span><strong>เป็นเพื่อนร่วมทางของ SME</strong> ลงมือ ติดตาม และปรับแผนร่วมกัน เพื่อไปให้ถึงเป้าหมายที่ตกลงไว้</span></p></div></div><LeadForm/></section>
</main><footer><div className="wrap footer-inner"><a href="https://www.sellsuki.co.th/" className="brand-logo footer-logo" aria-label="Sellsuki หน้าแรก"><img src="/sellsuki-logo.png" alt="Sellsuki" width="1667" height="834"/></a><p className="footer-promise">Sellsuki เป็นให้คุณได้ มากกว่าแค่คำว่า พาร์ทเนอร์ธุรกิจ เราพร้อมจะพา SMEs ไทย เติบโตไปไกลกว่าเดิม ด้วยแพลตฟอร์มและบริการ<span>ที่ครบ จบ ในที่เดียว</span></p><a href="#main">กลับด้านบน ↑</a></div></footer><div className="mobile-cta"><a className="button" href="#talk">คุยกับทีม Sellsuki <ArrowUpRight size={18}/></a></div></>}
