import { ArrowRight, MapPin, Camera, Compass, Megaphone, Code2, Clock, TrendingDown, UserMinus, MessagesSquare, MousePointerClick, CircleCheck } from 'lucide-react';
import BackToTop from './back-to-top';
import LeadForm from './lead-form';
import CustomerJourney from './customer-journey';
import ProblemApproach from './problem-approach';
const challenges=[
 {icon:MapPin,title:'คู่แข่งในพื้นที่เยอะขึ้น',text:'ลูกค้ามีหลายคลินิกให้เลือก ทั้งใกล้บ้านและใกล้ที่ทำงาน ทำอย่างไรให้เขานึกถึงเรา?'},
 {icon:Megaphone,title:'บนออนไลน์ ก็มีคู่แข่งเต็มไปหมด',text:'ลูกค้าเห็นทั้งโฆษณา รีวิว และโปรโมชันทุกวัน คลินิกเราจะเล่าอะไรให้เขาหยุดดู?'},
 {icon:Clock,title:'ลูกค้าใช้เวลาตัดสินใจนานขึ้น',text:'ทักมาถามแล้วกลับไปดูข้อมูล เปรียบเทียบอีกหลายที่ ระหว่างนั้นเราติดต่อดูแลเขาอย่างไร?'},
 {icon:TrendingDown,title:'วิธีเดิมเริ่มไม่ได้ผลเหมือนเดิม',text:'คอนเทนต์และโปรโมชันที่เคยได้ผล วันนี้อาจมีคนสนใจน้อยลง ควรลองปรับอะไรดี?'},
 {icon:UserMinus,title:'ลูกค้าเก่าไม่กลับมา',text:'เคยมาใช้บริการแล้ว แต่ไม่ได้ติดต่อกันอีก คลินิกจะชวนเขากลับมาดูแลตัวเองอย่างไร?'},
 {icon:MessagesSquare,title:'ทีมการตลาดยังไม่เข้าใจคลินิก',text:'มีทีมทำงานให้ แต่สิ่งที่สื่อสารยังไม่ตรงกับจุดเด่นของคลินิก ต้องอธิบายกันใหม่อยู่บ่อย ๆ'}
];
const teams=[{role:'กลยุทธ์และดูแลลูกค้า',icon:Compass,work:'คุยกับคุณให้เข้าใจบริการ ลูกค้า และเป้าหมาย วางแผนงาน พร้อมประสานงานระหว่างทีม',label:'ทีมงานที่คุณคุยด้วยตั้งแต่เริ่ม'}, {role:'คอนเทนต์และครีเอทีฟ',icon:Camera,work:'ช่วยคิดเรื่องที่จะเล่า เขียนข้อความ และวางภาพให้คนเข้าใจจุดเด่นของคลินิกและคุณหมอ',label:'ทีมงานที่ช่วยเล่าเรื่องคลินิก'}, {role:'โฆษณาและการค้นหา',icon:Megaphone,work:'ดูแลโฆษณา เว็บไซต์ และการค้นหาในพื้นที่ พร้อมติดตามว่าคนสนใจมาจากช่องทางไหน',label:'ทีมงานที่ช่วยให้ลูกค้าหาคุณเจอ'}, {role:'LINE ระบบและข้อมูล',icon:Code2,work:'วางการจัดกลุ่มลูกค้า การติดตาม และข้อมูลที่ทีมคลินิกใช้ทำงานต่อได้',label:'ทีมงานที่ช่วยให้คลินิกดูแลลูกค้าได้ครบ'}];
const executives=[
 {name:'Pattara Thurnsiri',role:'CEO & Co-Founder',label:'เข้าใจธุรกิจก่อนวางแผน',idea:'เริ่มจากเป้าหมายของคลินิก แล้ววางทิศทางให้การตลาด การขาย และการดูแลลูกค้าไปด้วยกัน',image:'/executive-nuntawit.png'},
 {name:'Nuntawit Janwaowam',role:'CPO & Co-Founder',label:'ออกแบบบริการจากโจทย์จริง',idea:'เลือกบริการและเครื่องมือให้ตอบสิ่งที่คลินิกต้องการ และช่วยให้ทีมทำงานได้สะดวกขึ้น',image:'/executive-pattara.png'},
 {name:'Pitchaporn Prakaiharn',role:'Chief Operating Officer',label:'ทำให้แผนเกิดขึ้นได้จริง',idea:'เชื่อมการทำงานของแต่ละทีม กำหนดหน้าที่ให้ชัด และติดตามงานให้เดินตามแผน',image:'/executive-pitchaporn.png'},
 {name:'Watchrapong Agsonchu',role:'Chief Technology Officer',label:'ให้ระบบช่วยแบ่งเบางาน',idea:'ลดงานซ้ำ เชื่อมข้อมูล และทำให้ทีมใช้ข้อมูลดูแลลูกค้าได้ง่ายขึ้น',image:'/executive-watchrapong.png'}
];
function PhotoSlot({label}:{label:string}){return <div className="photo-slot"><Camera aria-hidden="true"/><span>{label}</span><small>พื้นที่สำหรับภาพจริง</small></div>}
export default function Home(){return <>
<a className="skip" href="#main">ข้ามไปเนื้อหา</a>
<header className="header"><div className="nav wrap"><a href="https://www.sellsuki.co.th/" className="brand-logo" aria-label="Sellsuki หน้าแรก"><img src="/sellsuki-logo.png" alt="Sellsuki" width="1667" height="834"/></a><nav aria-label="เมนูหลัก"><a href="#solutions">บริการของ Sellsuki</a><a href="#team">ทีมการตลาดของเรา</a><a href="#experience">กว่า 10 ปีที่เติบโตไปกับธุรกิจไทย</a></nav><a className="button small" href="#talk">คุยกับทีม Sellsuki <ArrowRight size={22} strokeWidth={1.9} aria-hidden="true"/></a></div></header>
<main id="main">
<section className="hero wrap"><div className="hero-copy"><h1>เปลี่ยนคนที่ทักคลินิกมาแล้วหาย<br/>ให้เป็นลูกค้านัดหมายและมาซ้ำ</h1><p>จบปัญหาทักมาแล้วแต่ไปไม่ถึงนัด หรือไม่มีเวลาตามลูกค้าเก่า ให้ Sellsuki ดูแลตั้งแต่คอนเทนต์ โฆษณา จัดการนัดหมาย ไปจนถึงการดูแลลูกค้าเดิม</p><ul className="hero-chips"><li><CircleCheck size={22} aria-hidden="true"/>บริการการตลาดสำหรับคลินิกความงามและสุขภาพ</li><li><CircleCheck size={22} aria-hidden="true"/>10+ ปี ประสบการณ์ ดูแลธุรกิจไทย</li></ul><div className="hero-actions"><a className="button" href="#talk"><MousePointerClick size={20}/> ปรึกษาการตลาดคลินิก</a><a className="text-link" href="#solutions">ดูบริการของ Sellsuki <ArrowRight size={22} strokeWidth={1.9} aria-hidden="true"/></a></div></div><div className="hero-visual"><div className="photo-frame"><img src="/clinic-partners.png" alt="ที่ปรึกษาการตลาดของ Sellsuki กำลังพูดคุยกับเจ้าของคลินิกความงาม" width="1448" height="1086"/></div></div></section>
<section className="section wrap" id="challenges"><div className="challenge-intro"><div className="eyebrow"><span>PROBLEM</span></div><h2>คลินิกของคุณกำลังเจอเรื่องไหนอยู่บ้าง?</h2><p>ลองดูว่าเรื่องไหนตรงกับสิ่งที่คุณกำลังเจอ</p></div><div className="challenge-grid">{challenges.map((c,i)=><article key={c.title}><img className="challenge-bg" src={`/challenge-${i+1}.png`} alt="" width="1536" height="1024" loading="lazy"/><span className="challenge-icon"><c.icon size={23} strokeWidth={1.9} aria-hidden="true"/></span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
<section id="solutions" className="solutions section"><div className="wrap"><div className="section-heading"><div><div className="eyebrow"><span>บริการของ Sellsuki</span></div><h2>ช่วยหาลูกค้าใหม่<br/><span className="blue">ตั้งแต่ทำให้รู้จัก จนถึงวันนัดหมาย</span></h2></div><p>ดูแลทุกขั้นตอนของ Customer Journey ตั้งแต่การสร้างการรับรู้ ดึงดูดคนที่สนใจ ไปจนถึงติดตามและเปลี่ยน Lead ให้เป็นนัดหมาย</p></div><CustomerJourney/></div></section>
<section className="section wrap examples" id="examples"><div className="pa-head"><div className="eyebrow"><span>START FROM YOUR PROBLEM</span></div><h2>ถ้าคลินิกติดเรื่องนี้<br/>เราจะเริ่มช่วยอย่างไร?</h2><p>ตัวอย่างแนวทางทำงาน เพื่อให้เห็นภาพก่อนคุยรายละเอียดของคลินิกคุณ</p></div><ProblemApproach/></section>
<section className="growth-section section"><div className="wrap"><div className="clinic-brand-banner"><img src="/challenge-6.png" alt="" width="1536" height="1024" loading="lazy"/><div className="clinic-brand-copy"><h3>เราอยากเห็นคลินิกของคุณเติบโตไปได้ไกลกว่าเดิม</h3><p>เพราะเราเชื่อในความตั้งใจของคนทำธุรกิจ Sellsuki จึงพร้อมช่วย SME อย่างคุณ วางแผน ลงมือทำ<br className="banner-br"/>และพัฒนาการตลาดไปด้วยกัน เพื่อให้ธุรกิจเติบโตได้ในระยะยาว</p></div></div></div></section>
<section className="section wrap leadership" id="experience"><div className="leadership-intro"><div><div className="eyebrow"><span>กว่า 10 ปีที่เติบโตไปกับธุรกิจไทย</span></div><h2>เราได้ทำงานร่วมกับ SME ไทย<br/>มาตลอดกว่าทศวรรษ</h2></div><p>ตลอดเวลากว่า 10 ปี Sellsuki ได้ทำงานเคียงข้าง SME ไทยในวันที่เริ่มต้น ขยายช่องทางขาย และปรับการตลาดให้ไปต่อได้จริง ประสบการณ์เหล่านี้จึงกลายเป็นมุมมองที่ทีมพร้อมนำมาช่วยคิดให้กับคลินิกของคุณ</p></div><div className="executive-banner">{executives.map(e=><article key={e.name}><div className="executive-avatar"><img src={e.image} alt={`ภาพ ${e.name}`} width="2048" height="2048" loading="lazy"/></div><div className="executive-copy"><strong>{e.name}</strong><span className="executive-role">{e.role}</span><h3>{e.label}</h3><p>{e.idea}</p></div></article>)}</div></section>
<section className="section wrap talk lead-section" id="talk"><div className="lead-message"><div className="eyebrow"><span>เริ่มคุยกันได้เลย</span></div><h2>อยากให้การตลาดของคลินิก<br/>ดีขึ้นเรื่องไหน?</h2><p>บอกเราว่าตอนนี้กำลังติดอะไร แล้วทีมจะช่วยดูว่าควรเริ่มตรงไหน ไม่จำเป็นต้องมีแผนการตลาดมาก่อน</p><div className="brand-promise"><h3>สิ่งที่เราอยากให้คุณได้จากการทำงานด้วยกัน</h3><p><CircleCheck size={24} strokeWidth={1.8} aria-hidden="true"/> <span><strong>ทำอย่างมีกลยุทธ์</strong> เข้าใจปัญหาก่อนเลือกวิธีทำ</span></p><p><CircleCheck size={24} strokeWidth={1.8} aria-hidden="true"/> <span><strong>คุยรู้เรื่อง</strong> อธิบายงาน งบประมาณ และผลที่วัดได้ให้ชัด</span></p><p><CircleCheck size={24} strokeWidth={1.8} aria-hidden="true"/> <span><strong>เป็นเพื่อนร่วมทางของ SME</strong> ลงมือ ติดตาม และปรับแผนร่วมกัน เพื่อไปให้ถึงเป้าหมายที่ตกลงไว้</span></p></div></div><LeadForm/></section>
</main><footer><div className="wrap footer-inner"><a href="https://www.sellsuki.co.th/" className="brand-logo footer-logo" aria-label="Sellsuki หน้าแรก"><img src="/sellsuki-logo-footer.png" alt="Sellsuki" width="1667" height="834"/></a><p className="footer-promise">Sellsuki เป็นให้คุณได้ มากกว่าแค่คำว่า พาร์ทเนอร์ธุรกิจ เราพร้อมจะพา SMEs ไทย เติบโตไปไกลกว่าเดิม ด้วยแพลตฟอร์มและบริการ<span>ที่ครบ จบ ในที่เดียว</span></p></div></footer><BackToTop/><div className="mobile-cta"><a className="button" href="#talk">คุยกับทีม Sellsuki <ArrowRight size={22} strokeWidth={1.9} aria-hidden="true"/></a></div></>}
