import { ArrowRight, MapPin, Camera, Compass, Megaphone, Code2, Clock, TrendingDown, UserMinus, MessagesSquare, MousePointerClick } from 'lucide-react';
import BackToTop from './back-to-top';
import CookieConsent, { CookieSettingsButton } from './cookie-consent';
import LeadForm from './lead-form';
import CustomerJourney from './customer-journey';
import ProblemApproach from './problem-approach';
const challenges=[
 {icon:MapPin,title:'คู่แข่งในพื้นที่เยอะขึ้น',text:'ลูกค้ามีหลายคลินิกให้เลือก ทั้งใกล้บ้านและใกล้ที่ทำงาน ทำอย่างไรให้เขานึกถึงเรา?'},
 {icon:Megaphone,title:'บนออนไลน์ ก็มีคู่แข่งเต็มไปหมด',text:'ลูกค้าเห็นทั้งโฆษณา รีวิว และโปรโมชันทุกวัน คลินิกเราจะเล่าอะไรให้เขาหยุดดู?'},
 {icon:Clock,title:'ลูกค้าใช้เวลาตัดสินใจนานขึ้น',text:'ทักมาถามแล้วกลับไปดูข้อมูล เปรียบเทียบอีกหลายที่ ระหว่างนั้นเราติดต่อดูแลเขาอย่างไร?'},
 {icon:TrendingDown,title:'วิธีเดิมเริ่มไม่ได้ผลเหมือนเดิม',text:'คอนเทนต์และโปรโมชันที่เคยได้ผล วันนี้อาจมีคนสนใจน้อยลง ควรลองปรับอะไรดี?'},
 {icon:UserMinus,title:'ลูกค้าเก่าไม่กลับมา',text:'เคยมาใช้บริการแล้ว แต่ไม่ได้ติดต่อกันอีก คลินิกจะชวนเขากลับมาดูแลตัวเองอย่างไร?'},
 {icon:MessagesSquare,title:'ทีมการตลาดยังไม่เข้าใจคลินิก',text:'มีทีมทำงานให้ แต่สิ่งที่สื่อสารยังไม่ตรงกับจุดเด่นของคลินิก ต้องอธิบายกันใหม่อยู่บ่อย ๆ'}
];
const teams=[{role:'กลยุทธ์และดูแลลูกค้า',icon:Compass,work:'คุยกับคุณให้เข้าใจบริการ ลูกค้า และเป้าหมาย วางแผนงาน พร้อมประสานงานระหว่างทีม',label:'ทีมงานที่คุณคุยด้วยตั้งแต่เริ่ม'}, {role:'คอนเทนต์และครีเอทีฟ',icon:Camera,work:'ช่วยคิดเรื่องที่จะเล่า เขียนข้อความ และวางภาพให้คนเข้าใจจุดเด่นของคลินิกและคุณหมอ',label:'ทีมงานที่ช่วยเล่าเรื่องคลินิก'}, {role:'โฆษณาและการค้นหา',icon:Megaphone,work:'ดูแลโฆษณา เว็บไซต์ และการค้นหาในพื้นที่ พร้อมติดตามว่าคนสนใจมาจากช่องทางไหน',label:'ทีมงานที่ช่วยให้ลูกค้าหาคุณเจอ'}, {role:'LINE ระบบและข้อมูล',icon:Code2,work:'วางการจัดกลุ่มลูกค้า การติดตาม และข้อมูลที่ทีมคลินิกใช้ทำงานต่อได้',label:'ทีมงานที่ช่วยให้คลินิกดูแลลูกค้าได้ครบ'}];
const executives=[
 {name:'Pattara Thurnsiri',role:'CEO & Co-Founder',label:'เข้าใจธุรกิจก่อนวางแผน',idea:'เริ่มจากเป้าหมายของคลินิก แล้ววางทิศทางให้การตลาด การขาย และการดูแลลูกค้าไปด้วยกัน',image:'/executive-nuntawit.png'},
 {name:'Nuntawit Janwaowam',role:'CPO & Co-Founder',label:'ออกแบบบริการจากโจทย์จริง',idea:'เลือกบริการและเครื่องมือให้ตอบสิ่งที่คลินิกต้องการ และช่วยให้ทีมทำงานได้สะดวกขึ้น',image:'/executive-pattara.png'},
 {name:'Pitchaporn Prakaiharn',role:'Chief Operating Officer',label:'ทำให้แผนเกิดขึ้นได้จริง',idea:'เชื่อมการทำงานของแต่ละทีม กำหนดหน้าที่ให้ชัด และติดตามงานให้เดินตามแผน',image:'/executive-pitchaporn.png'},
 {name:'Watchrapong Agsonchu',role:'Chief Technology Officer',label:'ให้ระบบช่วยแบ่งเบางาน',idea:'ลดงานซ้ำ เชื่อมข้อมูล และทำให้ทีมใช้ข้อมูลดูแลลูกค้าได้ง่ายขึ้น',image:'/executive-watchrapong.png'}
];
function PhotoSlot({label}:{label:string}){return <div className="photo-slot"><Camera aria-hidden="true"/><span>{label}</span><small>พื้นที่สำหรับภาพจริง</small></div>}
const SolidCheck=()=><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true"><circle cx="12" cy="12" r="11" fill="#fff"/><path d="m7.4 12.3 3 3 6.2-6.4" fill="none" stroke="#111827" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/></svg>;
const BlueCheck=()=><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true"><circle cx="12" cy="12" r="11" fill="#32a9ff"/><path d="m7.4 12.3 3 3 6.2-6.4" fill="none" stroke="#fff" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/></svg>;
const FacebookMark=()=><svg viewBox="0 0 24 24" width="28" height="28" aria-hidden="true"><path fill="currentColor" d="M24 12a12 12 0 1 0-13.9 11.9v-8.4h-3V12h3V9.4c0-3 1.8-4.7 4.5-4.7 1.3 0 2.7.2 2.7.2v3h-1.5c-1.5 0-2 .9-2 1.9V12h3.4l-.5 3.5h-2.9v8.4A12 12 0 0 0 24 12Z"/></svg>;
const InstagramMark=()=><svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" strokeWidth="1.9" aria-hidden="true"><rect x="2.5" y="2.5" width="19" height="19" rx="5.5"/><circle cx="12" cy="12" r="4.3"/><circle cx="17.6" cy="6.4" r="1.1" fill="currentColor" stroke="none"/></svg>;
const XMark=()=><svg viewBox="0 0 24 24" width="26" height="26" aria-hidden="true"><path fill="currentColor" d="M17.8 2.3h3.3l-7.2 8.2 8.5 11.2h-6.6l-5.2-6.8-5.9 6.8H1.4l7.7-8.8L1 2.3h6.8l4.7 6.2 5.3-6.2Zm-1.2 17.4h1.8L6.6 4.2H4.6l12 15.5Z"/></svg>;
const LinkedInMark=()=><svg viewBox="0 0 24 24" width="28" height="28" aria-hidden="true"><path fill="currentColor" d="M20.4 2H3.6A1.6 1.6 0 0 0 2 3.6v16.8A1.6 1.6 0 0 0 3.6 22h16.8a1.6 1.6 0 0 0 1.6-1.6V3.6A1.6 1.6 0 0 0 20.4 2ZM8 19H5V9.5h3V19ZM6.5 8.2a1.7 1.7 0 1 1 0-3.5 1.7 1.7 0 0 1 0 3.5ZM19 19h-3v-4.6c0-1.1 0-2.5-1.5-2.5S12.8 13 12.8 14.3V19h-3V9.5h2.8v1.3h.1a3.1 3.1 0 0 1 2.8-1.5c3 0 3.5 2 3.5 4.5V19Z"/></svg>;
const YouTubeMark=()=><svg viewBox="0 0 24 24" width="30" height="30" aria-hidden="true"><path fill="currentColor" d="M23 7.2a3 3 0 0 0-2.1-2.1C19 4.6 12 4.6 12 4.6s-7 0-8.9.5A3 3 0 0 0 1 7.2 31 31 0 0 0 .5 12a31 31 0 0 0 .5 4.8 3 3 0 0 0 2.1 2.1c1.9.5 8.9.5 8.9.5s7 0 8.9-.5a3 3 0 0 0 2.1-2.1 31 31 0 0 0 .5-4.8 31 31 0 0 0-.5-4.8ZM9.7 15V9l5.8 3-5.8 3Z"/></svg>;
export default function Home(){return <>
<a className="skip" href="#main">ข้ามไปเนื้อหา</a>
<header className="header"><div className="nav wrap"><a href="https://www.sellsuki.co.th/" className="brand-logo" aria-label="Sellsuki หน้าแรก"><img src="/sellsuki-logo.png" alt="Sellsuki" width="1667" height="834"/></a><nav aria-label="เมนูหลัก"><a href="#solutions">บริการของ Sellsuki</a><a href="#team">ทีมการตลาดของเรา</a><a href="#experience">กว่า 10 ปีที่เติบโตไปกับธุรกิจไทย</a></nav><a className="button small" href="#talk">คุยกับทีม Sellsuki <ArrowRight size={22} strokeWidth={1.9} aria-hidden="true"/></a></div></header>
<main id="main">
<section className="hero wrap"><div className="hero-copy"><h1>เปลี่ยนคนที่ทักคลินิกมาแล้วหาย<br/>ให้เป็นลูกค้านัดหมายและมาซ้ำ</h1><p>จบปัญหาทักมาแล้วแต่ไปไม่ถึงนัด หรือไม่มีเวลาตามลูกค้าเก่า ให้ Sellsuki ดูแลตั้งแต่คอนเทนต์ โฆษณา จัดการนัดหมาย ไปจนถึงการดูแลลูกค้าเดิม</p><ul className="hero-chips"><li><SolidCheck/>บริการการตลาดสำหรับคลินิกความงามและสุขภาพ</li><li><SolidCheck/>10+ ปี ประสบการณ์ ดูแลธุรกิจไทย</li></ul><div className="hero-actions"><a className="button" href="#talk"><MousePointerClick size={20}/> ปรึกษาการตลาดคลินิก</a><a className="text-link" href="#solutions">ดูบริการของ Sellsuki <ArrowRight size={22} strokeWidth={1.9} aria-hidden="true"/></a></div></div><div className="hero-visual"><div className="photo-frame"><img src="/clinic-partners.png" alt="ที่ปรึกษาการตลาดของ Sellsuki กำลังพูดคุยกับเจ้าของคลินิกความงาม" width="1448" height="1086"/></div></div></section>
<section className="section wrap" id="challenges"><div className="challenge-intro"><div className="eyebrow"><span>PROBLEM</span></div><h2>คลินิกของคุณกำลังเจอเรื่องไหนอยู่บ้าง?</h2><p>ลองดูว่าเรื่องไหนตรงกับสิ่งที่คุณกำลังเจอ</p></div><div className="challenge-grid">{challenges.map((c,i)=><article key={c.title}><img className="challenge-bg" src={`/challenge-${i+1}.png`} alt="" width="1536" height="1024" loading="lazy"/><span className="challenge-icon"><c.icon size={23} strokeWidth={1.9} aria-hidden="true"/></span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
<section id="solutions" className="solutions section"><div className="wrap"><div className="section-heading"><div><div className="eyebrow"><span>บริการของ Sellsuki</span></div><h2>ช่วยหาลูกค้าใหม่<br/><span className="blue">ตั้งแต่ทำให้รู้จัก จนถึงวันนัดหมาย</span></h2></div><p>ดูแลทุกขั้นตอนของ Customer Journey ตั้งแต่การสร้างการรับรู้ ดึงดูดคนที่สนใจ<br/>ไปจนถึงติดตามและเปลี่ยน Lead ให้เป็นนัดหมาย</p></div><CustomerJourney/></div></section>
<section className="section wrap examples" id="examples"><div className="pa-head"><div className="eyebrow"><span>START FROM YOUR PROBLEM</span></div><h2>ถ้าคลินิกติดเรื่องนี้<br/>เราจะเริ่มช่วยอย่างไร?</h2><p>ตัวอย่างแนวทางทำงาน เพื่อให้เห็นภาพก่อนคุยรายละเอียดของคลินิกคุณ</p></div><ProblemApproach/></section>
<section className="growth-section section"><div className="wrap"><div className="clinic-brand-banner"><img src="/challenge-6.png" alt="" width="1536" height="1024" loading="lazy"/><div className="clinic-brand-copy"><h3>เราอยากเห็นคลินิกของคุณเติบโตไปได้ไกลกว่าเดิม</h3><p>เพราะเราเชื่อในความตั้งใจของคนทำธุรกิจ Sellsuki จึงพร้อมช่วย SME อย่างคุณ วางแผน ลงมือทำ<br className="banner-br"/>และพัฒนาการตลาดไปด้วยกัน เพื่อให้ธุรกิจเติบโตได้ในระยะยาว</p></div></div></div></section>
<section className="section wrap leadership" id="experience"><div className="leadership-intro"><div><div className="eyebrow"><span>กว่า 10 ปีที่เติบโตไปกับธุรกิจไทย</span></div><h2>เราได้ทำงานร่วมกับ SME ไทย<br/>มาตลอดกว่าทศวรรษ</h2></div><p>ตลอดเวลากว่า 10 ปี Sellsuki ได้ทำงานเคียงข้าง SME ไทยในวันที่เริ่มต้น ขยายช่องทางขาย และปรับการตลาดให้ไปต่อได้จริง ประสบการณ์เหล่านี้จึงกลายเป็นมุมมองที่ทีมพร้อมนำมาช่วยคิดให้กับคลินิกของคุณ</p></div><div className="executive-banner">{executives.map(e=><article key={e.name}><div className="executive-avatar"><img src={e.image} alt={`ภาพ ${e.name}`} width="2048" height="2048" loading="lazy"/></div><div className="executive-copy"><strong>{e.name}</strong><span className="executive-role">{e.role}</span><h3>{e.label}</h3><p>{e.idea}</p></div></article>)}</div></section>
<section className="section wrap talk lead-section" id="talk"><div className="lead-message"><div className="eyebrow"><span>เริ่มคุยกันได้เลย</span></div><h2>อยากให้การตลาดของคลินิก<br/>ดีขึ้นเรื่องไหน?</h2><p>บอกเราว่าตอนนี้กำลังติดอะไร แล้วทีมจะช่วยดูว่าควรเริ่มตรงไหน ไม่จำเป็นต้องมีแผนการตลาดมาก่อน</p><div className="brand-promise"><h3>สิ่งที่เราอยากให้คุณได้จากการทำงานด้วยกัน</h3><p><BlueCheck/> <span><strong>ทำอย่างมีกลยุทธ์</strong> เข้าใจปัญหาก่อนเลือกวิธีทำ</span></p><p><BlueCheck/> <span><strong>คุยรู้เรื่อง</strong> อธิบายงาน งบประมาณ และผลที่วัดได้ให้ชัด</span></p><p><BlueCheck/> <span><strong>เป็นเพื่อนร่วมทางของ SME</strong> ลงมือ ติดตาม และปรับแผนร่วมกัน เพื่อไปให้ถึงเป้าหมายที่ตกลงไว้</span></p></div></div><LeadForm/></section>
</main><footer><div className="wrap footer-main"><div className="footer-brand"><a href="https://www.sellsuki.co.th/" className="brand-logo footer-logo" aria-label="Sellsuki หน้าแรก"><img src="/sellsuki-logo-footer.png" alt="Sellsuki" width="1667" height="834"/></a><p className="footer-tagline"><span>Sellsuki เป็นให้คุณได้ มากกว่าแค่คำว่า พาร์ทเนอร์ธุรกิจ</span><span>เราพร้อมจะพา SMEs ไทย เติบโตไปไกลกว่าเดิม</span><span>ด้วยแพลตฟอร์มและบริการ ที่ครบ จบ ในที่เดียว</span></p></div><div className="footer-info"><div className="footer-contact"><h4>Address:</h4><address>Sellsuki Co.,Ltd.<br/>4Simplex, 3rd Floor, No. 10/39<br/>Ratchadapisek Road, Chankasem,<br/>Chatuchak, Bangkok 10900<br/>Thailand</address><h4>Contact:</h4><a href="tel:0900967526">090 096 7526</a></div><div className="footer-social"><a href="https://www.facebook.com/Sellsuki/" target="_blank" rel="noopener noreferrer" aria-label="Sellsuki Facebook"><FacebookMark/></a><a href="https://www.facebook.com/Sellsuki/" target="_blank" rel="noopener noreferrer" aria-label="Sellsuki Instagram"><InstagramMark/></a><a href="https://www.facebook.com/Sellsuki/" target="_blank" rel="noopener noreferrer" aria-label="Sellsuki X"><XMark/></a><a href="https://www.facebook.com/Sellsuki/" target="_blank" rel="noopener noreferrer" aria-label="Sellsuki LinkedIn"><LinkedInMark/></a><a href="https://page.line.me/pld0867p" target="_blank" rel="noopener noreferrer" aria-label="Sellsuki YouTube"><YouTubeMark/></a></div></div><nav className="footer-nav" aria-label="บริการ"><h4>บริการ</h4><a href="https://www.sellsuki.co.th/solutions/wizemoves" target="_blank" rel="noopener noreferrer">Wizemoves</a><a href="https://www.sellsuki.co.th/solutions/lineagency" target="_blank" rel="noopener noreferrer">LINE Agency</a><a href="https://www.sellsuki.co.th/" target="_blank" rel="noopener noreferrer">Sukispace</a><a href="https://www.sellsuki.co.th/solutions/akita" target="_blank" rel="noopener noreferrer">Akita</a></nav><nav className="footer-nav" aria-label="เกี่ยวกับเรา"><h4>เกี่ยวกับเรา</h4><a href="https://www.sellsuki.co.th/contact-us" target="_blank" rel="noopener noreferrer">ติดต่อเรา</a><a href="https://www.sellsuki.co.th/join-us" target="_blank" rel="noopener noreferrer">ร่วมงานกับเรา</a><a href="https://www.sellsuki.co.th/blog" target="_blank" rel="noopener noreferrer">บทความที่น่าสนใจ</a></nav></div><div className="wrap footer-bottom"><p>© 2026 sellsuki. All rights reserved.</p><nav aria-label="นโยบาย"><a href="https://www.sellsuki.co.th/policy" target="_blank" rel="noopener noreferrer">Privacy Policy</a><a href="https://www.sellsuki.co.th/terms-of-use" target="_blank" rel="noopener noreferrer">Terms of Service</a><CookieSettingsButton/></nav></div></footer><BackToTop/><CookieConsent/><div className="mobile-cta"><a className="button" href="#talk">คุยกับทีม Sellsuki <ArrowRight size={22} strokeWidth={1.9} aria-hidden="true"/></a></div></>}
